#!/bin/bash

# ==========================================
# Configuration
# ==========================================
# Path to your Zulu JDK 25
JDK_PATH="/home/fruc/Documents/zulu25.34.17-ca-fx-jdk25.0.3-linux_x64"
JPACKAGE="$JDK_PATH/bin/jpackage"
MODULE_PATH="$JDK_PATH/jmods"
VERSION="1.0-SNAPSHOT"

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}----------------------------------------${NC}"
echo -e "${GREEN}Building Chess AppImages (Fat Jar Mode)${NC}"
echo -e "${GREEN}----------------------------------------${NC}"

# 1. Set JAVA_HOME to ensure Maven uses the correct JDK
export JAVA_HOME="$JDK_PATH"
export PATH="$JAVA_HOME/bin:$PATH"

echo "[INFO] Using Java: $(java -version 2>&1 | head -n 1)"

# 2. Clean and Build All Modules
echo "[1/4] Cleaning and building all modules..."
mvn clean package -q
if [ $? -ne 0 ]; then
    echo -e "${RED}ERROR: Maven build failed. Aborting.${NC}"
    exit 1
fi
echo -e "${GREEN}[OK] Maven build successful.${NC}"

# ==========================================
# Build Client AppImage
# ==========================================
echo "[2/4] Building Client AppImage..."

# Find the FAT JAR (generated by maven-shade-plugin)
CLIENT_JAR=$(ls client/target/*-client-*.jar 2>/dev/null | head -n 1)
if [ -z "$CLIENT_JAR" ]; then
    echo -e "${RED}ERROR: Client JAR not found in client/target/${NC}"
    exit 1
fi
CLIENT_JAR_NAME=$(basename "$CLIENT_JAR")
echo "   Packaging: $CLIENT_JAR_NAME"

"$JPACKAGE" \
    --input client/target/ \
    --name ChessClient \
    --main-jar "$CLIENT_JAR_NAME" \
    --main-class com.chess.client.ClientMain \
    --type app-image \
    --java-options "--enable-native-access=ALL-UNNAMED"

if [ $? -ne 0 ]; then
    echo -e "${RED}ERROR: Failed to build Client AppImage.${NC}"
    exit 1
fi
echo -e "${GREEN}[OK] Client AppImage created: ChessClient/${NC}"

# ==========================================
# Build Server AppImage
# ==========================================
echo "[3/4] Building Server AppImage..."

# Find the FAT JAR for server
SERVER_JAR=$(ls server/target/*-server-*.jar 2>/dev/null | head -n 1)
if [ -z "$SERVER_JAR" ]; then
    echo -e "${RED}ERROR: Server JAR not found in server/target/${NC}"
    exit 1
fi
SERVER_JAR_NAME=$(basename "$SERVER_JAR")
echo "   Packaging: $SERVER_JAR_NAME"

"$JPACKAGE" \
    --input server/target/ \
    --name ChessServer \
    --main-jar "$SERVER_JAR_NAME" \
    --main-class com.chess.server.ServerMain \
    --type app-image \
    --java-options "--enable-native-access=ALL-UNNAMED"

if [ $? -ne 0 ]; then
    echo -e "${RED}ERROR: Failed to build Server AppImage.${NC}"
    exit 1
fi
echo -e "${GREEN}[OK] Server AppImage created: ChessServer/${NC}"

# ==========================================
# Finish
# ==========================================
echo -e "${GREEN}----------------------------------------${NC}"
echo -e "${GREEN}Done!${NC}"
echo -e "To run Client:  ${GREEN}./ChessClient/bin/ChessClient${NC}"
echo -e "To run Server:  ${GREEN}./ChessServer/bin/ChessServer${NC}"
echo -e "${GREEN}----------------------------------------${NC}"
